create table dbo.annual_refugees (
Year                       int         not null,
"Country of asylum"        varchar(50) not null,
"Number of Refugees"       int         not null,
"Number of Asylum-seekers" int         not null
)

alter table dbo.annual_refugees
	add constraint pk_annual_refugees primary key nonclustered (Year, "Country of asylum")

insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (1998, 'France', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (1999, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (1999, 'Thailand', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Australia', 5, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Canada', 0, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Germany', 0, 22)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Netherlands (Kingdom of the)', 5, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2000, 'Thailand', 0, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'Australia', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'Germany', 0, 19)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'Netherlands (Kingdom of the)', 7, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'Thailand', 0, 20)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2001, 'United States of America', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Australia', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Canada', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Denmark', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Germany', 225, 40)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Netherlands (Kingdom of the)', 9, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2002, 'Thailand', 0, 15)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Australia', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Canada', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Denmark', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Germany', 258, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Netherlands (Kingdom of the)', 14, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'Thailand', 0, 18)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2003, 'United States of America', 7, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Australia', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Canada', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Denmark', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'United Kingdom of Great Britain and Northern Ireland', 17, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Germany', 276, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Netherlands (Kingdom of the)', 15, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Switzerland', 0, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'Thailand', 0, 15)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2004, 'United States of America', 9, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Australia', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Canada', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Denmark', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'United Kingdom of Great Britain and Northern Ireland', 33, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Germany', 193, 42)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Netherlands (Kingdom of the)', 18, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Sweden', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'Switzerland', 0, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2005, 'United States of America', 9, 13)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Australia', 8, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Canada', 5, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Denmark', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'United Kingdom of Great Britain and Northern Ireland', 64, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Germany', 238, 21)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Kyrgyzstan', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Netherlands (Kingdom of the)', 20, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Norway', 5, 17)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Sweden', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'Switzerland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2006, 'United States of America', 29, 19)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Australia', 15, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Belgium', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Cambodia', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Canada', 5, 126)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Denmark', 8, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'United Kingdom of Great Britain and Northern Ireland', 281, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Germany', 204, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Ireland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Kyrgyzstan', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Netherlands (Kingdom of the)', 27, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Norway', 9, 69)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Russian Federation', 0, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Sweden', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'Switzerland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2007, 'United States of America', 22, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Australia', 14, 19)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Belgium', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Canada', 5, 126)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Denmark', 8, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'United Kingdom of Great Britain and Northern Ireland', 570, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Germany', 180, 13)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Ireland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Kyrgyzstan', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Netherlands (Kingdom of the)', 29, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Norway', 13, 23)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Russian Federation', 6, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Sweden', 7, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'Switzerland', 6, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2008, 'United States of America', 22, 13)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Australia', 15, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Belgium', 13, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Canada', 5, 59)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Denmark', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'United Kingdom of Great Britain and Northern Ireland', 574, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Germany', 156, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Ireland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Kyrgyzstan', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Netherlands (Kingdom of the)', 31, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Norway', 14, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Russian Federation', 10, 21)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Sweden', 8, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'Switzerland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2009, 'United States of America', 25, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Australia', 25, 33)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Belgium', 22, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Canada', 23, 179)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Denmark', 9, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'United Kingdom of Great Britain and Northern Ireland', 581, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Germany', 146, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Ireland', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Kyrgyzstan', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Netherlands (Kingdom of the)', 32, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Norway', 14, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Russian Federation', 14, 16)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Sweden', 8, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'Switzerland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2010, 'United States of America', 25, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Australia', 29, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Belgium', 31, 32)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Canada', 64, 393)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Denmark', 14, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'United Kingdom of Great Britain and Northern Ireland', 603, 59)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Germany', 193, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Netherlands (Kingdom of the)', 36, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Norway', 14, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Russian Federation', 18, 35)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Sweden', 9, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'Switzerland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2011, 'United States of America', 25, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Australia', 29, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Belgium', 61, 99)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Canada', 119, 822)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Denmark', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'United Kingdom of Great Britain and Northern Ireland', 619, 40)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Germany', 138, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Netherlands (Kingdom of the)', 58, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Norway', 14, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Russian Federation', 44, 29)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Sweden', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'Switzerland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2012, 'United States of America', 23, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Australia', 30, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Belgium', 68, 22)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Canada', 127, 710)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Denmark', 9, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'France', 0, 42)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'United Kingdom of Great Britain and Northern Ireland', 630, 56)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Germany', 112, 83)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Luxembourg', 5, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Netherlands (Kingdom of the)', 58, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Norway', 14, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Russian Federation', 74, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'Sweden', 8, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2013, 'United States of America', 23, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Australia', 30, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Belgium', 66, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Canada', 126, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Denmark', 10, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'France', 146, 35)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'United Kingdom of Great Britain and Northern Ireland', 622, 59)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Germany', 104, 84)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Luxembourg', 6, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Netherlands (Kingdom of the)', 59, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Norway', 14, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Russian Federation', 56, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'Sweden', 9, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2014, 'United States of America', 22, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Australia', 26, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Belgium', 46, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Canada', 126, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Chile', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Denmark', 10, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'France', 0, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'United Kingdom of Great Britain and Northern Ireland', 608, 47)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Germany', 101, 114)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Kuwait', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Luxembourg', 6, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Netherlands (Kingdom of the)', 56, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Norway', 13, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Russian Federation', 72, 15)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Spain', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'Sweden', 6, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2015, 'United States of America', 19, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Australia', 22, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Belgium', 36, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Canada', 485, 313)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Denmark', 10, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'France', 0, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'United Kingdom of Great Britain and Northern Ireland', 585, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Germany', 95, 135)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Ireland', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Kuwait', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Luxembourg', 12, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Netherlands (Kingdom of the)', 55, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Norway', 12, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Russian Federation', 79, 11)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'Sweden', 5, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2016, 'United States of America', 13, 13)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Australia', 19, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Belgium', 36, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Canada', 484, 409)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Denmark', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'France', 5, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'United Kingdom of Great Britain and Northern Ireland', 362, 36)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Germany', 92, 75)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Ireland', 5, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Luxembourg', 12, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Netherlands (Kingdom of the)', 48, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Norway', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Russian Federation', 77, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'Sweden', 5, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2017, 'United States of America', 12, 25)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Australia', 19, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Belgium', 36, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Canada', 478, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Denmark', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'France', 0, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'United Kingdom of Great Britain and Northern Ireland', 81, 29)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Germany', 34, 57)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Ireland', 7, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Luxembourg', 12, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Netherlands (Kingdom of the)', 46, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Russian Federation', 57, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'Sweden', 5, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2018, 'United States of America', 8, 35)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Australia', 18, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Belgium', 34, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Canada', 412, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Denmark', 8, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'United Kingdom of Great Britain and Northern Ireland', 78, 24)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Germany', 85, 39)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Ireland', 7, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Luxembourg', 11, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Netherlands (Kingdom of the)', 39, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Russian Federation', 50, 7)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'Sweden', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2019, 'United States of America', 6, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Australia', 7, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Belgium', 32, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Canada', 370, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Denmark', 6, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'United Kingdom of Great Britain and Northern Ireland', 72, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Germany', 85, 12)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Ireland', 7, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Luxembourg', 11, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Netherlands (Kingdom of the)', 35, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'Russian Federation', 53, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2020, 'United States of America', 6, 26)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Australia', 0, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Belgium', 32, 10)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Canada', 255, 17)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'United Kingdom of Great Britain and Northern Ireland', 51, 21)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Germany', 89, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Ireland', 9, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Luxembourg', 11, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Netherlands (Kingdom of the)', 27, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'Russian Federation', 43, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2021, 'United States of America', 6, 36)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Australia', 0, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Belgium', 28, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Canada', 33, 16)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'United Kingdom of Great Britain and Northern Ireland', 35, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Germany', 91, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Ireland', 8, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Luxembourg', 11, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Netherlands (Kingdom of the)', 12, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Russian Federation', 37, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'Sweden', 0, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2022, 'United States of America', 7, 63)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Australia', 0, 14)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Belgium', 18, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Canada', 26, 6)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'United Kingdom of Great Britain and Northern Ireland', 24, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Germany', 89, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Ireland', 11, 9)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Luxembourg', 11, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Netherlands (Kingdom of the)', 20, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'Russian Federation', 28, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2023, 'United States of America', 7, 47)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Australia', 0, 13)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Belgium', 16, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Canada', 33, 5)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'United Kingdom of Great Britain and Northern Ireland', 20, 29)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Germany', 92, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Ireland', 11, 8)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Israel', 5, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Luxembourg', 8, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Netherlands (Kingdom of the)', 25, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'Russian Federation', 27, 0)
insert into annual_refugees (Year, "Country of asylum", "Number of Refugees", "Number of Asylum-seekers") values (2024, 'United States of America', 7, 45)

select * from annual_refugees